_wandb:
    value:
        cli_version: 0.24.0
        e:
            1lvdl79cczhl31mt5po1stmcramaao7g:
                codePath: c:\Users\Arn\Projects\dynamic-pricing\notebooks\DP_parquet (3).ipynb
                codePathLocal: DP_parquet (3).ipynb
                cpu_count: 4
                cpu_count_logical: 8
                disk:
                    /:
                        total: "511200718848"
                        used: "90871263232"
                email: niharikareddy6902@gmail.com
                executable: c:\Users\Arn\Projects\dynamic-pricing\.venv\Scripts\python.exe
                git:
                    commit: b7e6c1d9d0ebb175a776b18ca49967a98d337862
                    remote: https://github.com/arn-niharika/dynamic-pricing.git
                host: DESKTOP-EFI0VK9
                memory:
                    total: "16831672320"
                os: Windows-10-10.0.19045-SP0
                program: c:\Users\Arn\Projects\dynamic-pricing\notebooks\DP_parquet (3).ipynb
                python: CPython 3.11.4
                root: c:\Users\Arn\Projects\dynamic-pricing\notebooks
                startedAt: "2026-01-19T08:40:52.598124Z"
                writerId: 1lvdl79cczhl31mt5po1stmcramaao7g
        m: []
        python_version: 3.11.4
        t:
            "1":
                - 5
                - 6
                - 53
            "2":
                - 5
                - 6
                - 8
                - 53
            "3":
                - 2
                - 13
                - 15
                - 16
            "4": 3.11.4
            "5": 0.24.0
            "8":
                - 1
                - 3
            "12": 0.24.0
            "13": windows-amd64
algorithms:
    value:
        - LinearRegression
        - RandomForest
        - XGBoost
        - GradientBoosting
feature_engineering:
    value: advanced
model_family:
    value: ensemble
random_state:
    value: 42
sklearn_version:
    value: 1.4.2
test_size:
    value: 0.2
